theme: jekyll-theme-minimal
logo: IMG_4859.JPG
description: Ph.D. Candidate| Transportation Engineering| Smart Cities| Coder| Interested in ML/AI Algorithms|
#show_downloads: true
github: https://github.com/gitpeck
linkedin: linkedin
