title: Abhilasha Saroj
theme: jekyll-theme-minimal
logo: IMG_4859.JPG
description: [CV](/Abhilasha Saroj_CV_11Oct2019.pdf)|Ph.D. Candidate| Georgia Tech| Transportation Engineering| Smart Cities| Coder| ML/AI Algorithms
#show_downloads: true
