title: Abhilasha Saroj
theme: jekyll-theme-minimal
logo: IMG_4859.JPG
description: Ph.D. Candidate| Georgia Tech| Transportation Engineering| Smart Cities| Coder| ML/AI Algorithms| (email: asaroj3@gatech.edu)
#show_downloads: true
