theme: jekyll-theme-minimal
logo: IMG_4859.JPG
description: Ph.D. Candidate| Georgia Tech| Transportation Engineering| Smart Cities| Coder| ML/AI Algorithms
#show_downloads: true
github: https://github.com/gitpeck
linkedin: linkedin
