title: Abhilasha Saroj
#theme: jekyll-theme-minimal
logo: IMG_4859.JPG
description: Ph.D. Candidate| Georgia Tech| Transportation Engineering| Smart Cities| Coder| ML/AI Algorithms
minimal_mistakes_skin: "plum" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#show_downloads: true
