title: Abhilasha Saroj
#minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
theme: jekyll-theme-minimal
logo: IMG_4859.JPG
description: Ph.D. Candidate| Georgia Tech| Transportation Engineering| Smart Cities| Coder| ML/AI Algorithms|(asaroj3@gatech.edu)
#show_downloads: true
