title: Abhilasha Saroj
#minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
theme: jekyll-theme-minimal
logo: IMG_4859.JPG
description: Ph.D. Candidate @ Georgia Tech| Transportation Systems Engineering| Smart Cities| [Linkedin](https://www.linkedin.com/in/abhilasha-saroj-gatech/)| [Github](https://github.com/gitpeck) 
